### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by GingkoFr** [kurkle/color#8]
About kurkle/color :

How do I install it?
How can I set it on a web site?
Which file(s) should I use?

**Comment by kurkle** [comment]
Hmm, how did I miss this.

You are right, the documentation is very much missing.
What were you planning to do with it on a website? (could possibly be a case for an example)

**Comment by GingkoFr** [comment]
Hello,
I think I forgot.
 On that time I was looking for a way to generate graphical SVG pictures.
Finally I made it without any library.
